/*
 * This source file was generated by the Gradle 'init' task
 */
package com.weatherboi

import kotlin.test.Test
import kotlin.test.assertTrue

class AppTest {
    @Test fun appCanGetWeatherInfoForClearSky() {
        val info = getWeatherInfo(0, true)
        assertTrue(info.description.contains("Clear"), "Clear sky should be recognized")
    }

    @Test fun appCanGetWeatherInfoForOvercast() {
        val info = getWeatherInfo(3, true)
        assertTrue(info.description.contains("Overcast"), "Overcast should be recognized")
    }

    @Test fun appCanStripAnsiCodes() {
        val stripped = stripAnsi("\u001B[1;31mHello\u001B[0m")
        assertTrue(stripped == "Hello", "ANSI codes should be stripped")
    }
}